### ISSUE TITLE
Deployment to the production environment

### ISSUE THREAD

**Issue by uemuramikio** [shooketh/petal#3]
* Code review
* Client
  * Improved client code 
  * Using petal in Urashima
* Deployment
  * Improved deployment
  * Multiple regions and zones
  * Best machine type and storage
* Document
  * Deployment Guide
  * How to Use

**Comment by uemuramikio** [comment]
### Autoscaling
* Improved deployment
Simplify the current complex and laborious deployment process. ([Deployment Guide](https://github.com/shooketh/petal/wiki/Deployment-Guide))
* Autoscaling based on instance usage
Instances are located in multiple regions and zones.

**Comment by uemuramikio** [comment]
### Document
* Deployment Guide
Include content about autoscaling.
* How to Use

**Comment by uemuramikio** [comment]
### Deployment to the production environment
Determine the best machine type and storage for the production environment and start operations.

**Comment by cnlangzi** [comment]
> ### Autoscaling
> * Improved deployment
>   Simplify the current complex and laborious deployment process. ([Deployment Guide](https://github.com/shooketh/petal/wiki/Deployment-Guide))
> * Autoscaling based on instance usage
>   Instances are located in multiple regions and zones.
>   Consider whether [Managed instance groups](https://cloud.google.com/compute/docs/instance-groups#managed_instance_groups) can be used.

Yes. it is better to use ManagedInstanceGroup.  Two instance groups are needed to setup. one is for etc, another is for petal.
